# Directorio de trabajo inicial
working_directory = "D:\\"

# Configuración de shell
[shell]
program = "C:\\Program Files\\PowerShell\\7\\pwsh.exe"
args = ["-NoExit", "-Command", ". $PROFILE"]

# Configuración de fuentes
[font]
size = 10.3

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "FantasqueSansM Nerd Font Mono"
style = "Bold Italic"

# Configuración para el peso de la fuente
[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

# Configuración de colores
[colors.primary]
background = "#1a1b26"
foreground = "#CAD3F5"
dim_foreground = "#CAD3F5"
bright_foreground = "#CAD3F5"

[colors.cursor]
text = "#24273A"
cursor = "#F4DBD6"

[colors.vi_mode_cursor]
text = "#24273A"
cursor = "#B7BDF8"

[colors.search.matches]
foreground = "#24273A"
background = "#A5ADCB"

[colors.search.focused_match]
foreground = "#24273A"
background = "#A6DA95"

[colors.hints.start]
foreground = "#24273A"
background = "#EED49F"

[colors.hints.end]
foreground = "#24273A"
background = "#A5ADCB"

[colors.selection]
text = "#24273A"
background = "#F4DBD6"

[colors.normal]
black = "#494D64"
red = "#ED8796"
green = "#A6DA95"
yellow = "#EED49F"
blue = "#8AADF4"
magenta = "#F5BDE6"
cyan = "#8BD5CA"
white = "#B8C0E0"

[colors.bright]
black = "#5B6078"
red = "#ED8796"
green = "#A6DA95"
yellow = "#EED49F"
blue = "#8AADF4"
magenta = "#F5BDE6"
cyan = "#8BD5CA"
white = "#A5ADCB"

[colors.dim]
black = "#494D64"
red = "#ED8796"
green = "#A6DA95"
yellow = "#EED49F"
blue = "#8AADF4"
magenta = "#F5BDE6"
cyan = "#8BD5CA"
white = "#B8C0E0"

[[colors.indexed_colors]]
index = 16
color = "#F5A97F"

[[colors.indexed_colors]]
index = 17
color = "#F4DBD6"

# Configuración de atajos de teclado
[[keyboard.bindings]]
key = "V"
mods = "Control"
action = "Paste"

# [[keyboard.bindings]]
# key = "C"
# mods = "Control"
# action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

# [[keyboard.bindings]]
# key = "A"
# mods = "Control"
# action = "SelectAll"

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "SpawnNewInstance"

[[keyboard.bindings]]
key = "Q"
mods = "Alt"
action = "Quit"

[[keyboard.bindings]]
key = "Return"
mods = "Alt"
action = "ToggleFullscreen"

[[keyboard.bindings]]
key = "Plus"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

# Configuración de la ventana
[window.padding]
x = 4
y = 0

# Configuración del ratón
[mouse]
hide_when_typing = false

# Configuración de selección
[selection]
save_to_clipboard = true

# Configuración de cursor
[cursor]
blink_interval = 750

[cursor.style]
shape = "Block"
blinking = "On"
